- name: "jaeger-ui"
  # <service name>.<namespace>
  target: "simple-query.observability"
  ports:
    local: 8686    # Same port as remote since it's the UI standard port
    remote: 16686   # Jaeger UI default port
  options:
    retry_interval: 5s
    max_retries: 30
    health_check_interval: 10s
    # This is true by default and ignores max_retries
    persistent_connection: false
  # local_dns:
  #   enabled: true
  #   hostname: "jaeger.localhost"  # Optional (it doesn't work yet), if you want to access it through a nice local domain
  pod_selector:
    label: "app.kubernetes.io/instance=simple"

- name: "argocd-ui"
  target: "argocd-server.argocd"
  ports:
    local: 8080    # custom port
    remote: 8080   # https
  options:
    retry_interval: 5s
    # max_retries: 30
    health_check_interval: 10s
    # This is true by default and ignores max_retries
    persistent_connection: true
  # local_dns:
  #   enabled: true
  #   hostname: "argocd.localhost"  # Optional (it doesn't work yet), if you want to access it through a nice local domain
  pod_selector:
    label: "app.kubernetes.io/name=argocd-server"

- name: "grafana-ui"
  target: "grafana.monitoring"
  ports:
    local: 3001  
    remote: 3000   
  options:
    retry_interval: 5s
    max_retries: 30
    health_check_interval: 10s
  # local_dns:
  #   enabled: true
  #   hostname: "grafana.localhost"  # Optional (it doesn't work yet), if you want to access it through a nice local domain
  pod_selector:
    label: "app.kubernetes.io/name=grafana"

- name: "postgres"
  target: "postgres.tr"
  ports:
    local: 5434 
    remote: 5432   
  options:
    retry_interval: 5s
    max_retries: 30
    health_check_interval: 10s
  # local_dns:
  #   enabled: true
  #   hostname: "grafana.localhost"  # Optional (it doesn't work yet), if you want to access it through a nice local domain
  # pod_selector:
  #   label: "app=postgres"

- name: "longhorn"
  target: "longhorn-frontend.longhorn-system"
  ports:
    local: 8082 
    remote: 8000
  options:
    retry_interval: 5s
    max_retries: 30
    health_check_interval: 10s
  # local_dns:
  #   enabled: true
  #   hostname: "grafana.localhost"  # Optional (it doesn't work yet), if you want to access it through a nice local domain
  pod_selector:
    label: "app=longhorn-ui"

