name: lint

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  DOCKERHUB_REPO: kainlite/gitops-operator

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt,clippy

      - uses: Swatinem/rust-cache@v2

      - run: cargo fmt -- --check

      - uses: giraffate/clippy-action@v1
        with:
          reporter: 'github-pr-review'
          github_token: ${{ secrets.GITHUB_TOKEN }}
